version: "3.3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: psychotesting
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      MYSQL_DB: psychotesting
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_HOST: mysql
    depends_on:
      - mysql
  frontend:
    build:
      context: ./client
    command: sh -c "serve -s dist"
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - backend