# Generated by Django 4.0.6 on 2022-07-21 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSelectable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('has_extra_data', models.BooleanField(default=False, verbose_name='Имеет дополнительную информацию')),
                ('index_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер ответа')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': '3 Answers',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Без названия', max_length=255, verbose_name='Название организации')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': '1 Organizations',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'Single (radio)'), (2, 'Multiple (checkbox)'), (3, 'Text field'), (4, 'Select field'), (5, 'Date field')], default=1, verbose_name='Тип вопроса')),
                ('question_text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('index_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер вопроса')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Является активным')),
                ('has_required_answer', models.BooleanField(default=True, verbose_name='Ответ на данный вопрос обязателен')),
                ('is_common_for_all_tests', models.BooleanField(default=False, verbose_name='Является общим для всех тестов')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': '2 Questions',
                'ordering': ('index_number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время прохождения теста')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'QuestionaryData',
                'verbose_name_plural': 'QuestionaryData',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Ответ (текстовый)')),
                ('answer_date', models.DateField(blank=True, null=True, verbose_name='Ответ (дата)')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация к ответу')),
                ('answer_selectable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psycho_forms.answerselectable', verbose_name='Ответ(выбираемый)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psycho_forms.question', verbose_name='Вопрос')),
                ('questionary_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psycho_forms.questionarydata', verbose_name='Данные анкеты')),
            ],
            options={
                'verbose_name': 'TestResult',
                'verbose_name_plural': '4 TestResults',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('extra_data', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='Вступительный текст')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Является активным')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psycho_forms.organization', verbose_name='Организация(владелец теста)')),
            ],
            options={
                'verbose_name': 'TestData',
                'verbose_name_plural': '1 TestsData',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='questionarydata',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psycho_forms.testdata', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psycho_forms.testdata', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answerselectable',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psycho_forms.question', verbose_name='Вопрос'),
        ),
    ]
