# Generated by Django 4.0.5 on 2022-06-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerselectable',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psycho_forms.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Single (radio)'), (2, 'Multiple (checkbox)'), (3, 'Text field'), (4, 'Select field'), (5, 'Date field')], default=1, verbose_name='Тип вопроса'),
        ),
    ]
