# Generated by Django 4.0.5 on 2022-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('id',), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='testdata',
            name='index_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер теста'),
        ),
        migrations.AlterField(
            model_name='answerselectable',
            name='answer_text',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
    ]
