# Generated by Django 4.0.5 on 2022-06-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_forms', '0002_alter_answerselectable_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='organisation',
            new_name='organization',
        ),
    ]
