# Generated by Django 4.0.5 on 2022-06-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_forms', '0003_rename_organisation_testdata_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default='Без названия', max_length=255, verbose_name='Название организации'),
        ),
    ]
