# Generated by Django 4.0.5 on 2022-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psycho_forms', '0005_alter_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Вступительный текст'),
        ),
    ]
